name: Daily Website Update (auto-PR)

on:
  schedule:
    - cron: "0 11 * * *"   # 4:00 AM Pacific / 11:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.Blocker_Fix }}

      - name: Configure git
        run: |
          git config user.name "nestfund-bot"
          git config user.email "bot@nestfund.local"

      - name: Fetch all branches
        run: git fetch --all --prune

      - name: Create auto-update branch
        run: |
          git checkout -b auto/daily-website-update

      - name: Detect changes
        run: |
          echo "Checking for changes..."
          git diff --exit-code main || echo "changes=true" >> $GITHUB_ENV

      - name: Commit changes (if any)
        if: env.changes == 'true'
        run: |
          git add -A
          git commit -m "Auto-update site content from daily workflow"

      - name: Push branch
        if: env.changes == 'true'
        run: |
          git push --force --set-upstream origin auto/daily-website-update

      - name: Create PR
        if: env.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.Blocker_Fix }}
          title: "Daily Website Update – ${{ github.run_id }}"
          branch: auto/daily-website-update
          base: main
          draft: true
          labels: needs-approval
          body: |
            Auto-PR from daily workflow.
            See Action logs for changed files.
