name: Daily Website Update (PR from feature)

on:
  schedule:
    - cron: "45 10 * * *"   # 3:45 AM Pacific = 10:45 UTC
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure git
        run: |
          git config user.name "nestfund-bot"
          git config user.email "bot@nestfund.local"

      - name: Fetch all branches
        run: git fetch --all --prune

      - name: Merge feature into PR branch
        env:
          FEATURE_BRANCH:  feature/day-07-subpages-calculator-grants   # <-- CHANGE to your branch with edits
        run: |
          git checkout -B auto/daily-website-update
          if git merge --no-ff "origin/${FEATURE_BRANCH}" -m "Auto-merge ${FEATURE_BRANCH} into auto/daily"; then
            echo "Merge OK"
          else
            echo "Merge conflict. Resolve in repo and re-run."; exit 1
          fi

      - name: Show changed files (debug)
        run: |
          echo "Last commit:" && git --no-pager log -1 --oneline
          echo "Changed files:" && git diff --name-only HEAD~1..HEAD || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Daily Website Update – ${{ github.run_id }}"
          branch: auto/daily-website-update   # source
          base: main                          # target
          draft: true
          body: |
            Auto-PR from feature branch into main.
            See Action logs for the changed files list.
